/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#ffb95f',
        'on-secondary': '#472a00',
        'secondary': '#ffb95f',
        'primary-fixed-dim': '#4de082',
        'surface-tint': '#4de082',
        'primary-container': '#4ade80',
        'on-tertiary-fixed-variant': '#6c3a0f',
        'on-secondary-fixed': '#2a1700',
        'on-tertiary-fixed': '#301400',
        'outline-variant': '#3d4a3e',
        'surface-container-highest': '#353534',
        'inverse-on-surface': '#313030',
        'surface-variant': '#353534',
        'on-secondary-fixed-variant': '#653e00',
        'on-primary-container': '#005e2d',
        'on-background': '#e5e2e1',
        'on-error': '#690005',
        'tertiary-fixed': '#ffdcc6',
        'surface-container-lowest': '#0e0e0e',
        'background': '#131313',
        'primary-fixed': '#6dfe9c',
        'inverse-surface': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'tertiary-fixed-dim': '#ffb784',
        'surface-container-low': '#1c1b1b',
        'on-primary-fixed': '#00210c',
        'surface-container-high': '#2a2a2a',
        'error': '#ffb4ab',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#5b3800',
        'tertiary-container': '#ffb47f',
        'on-primary-fixed-variant': '#005227',
        'primary': '#6bfb9a',
        'on-surface-variant': '#bccabb',
        'on-tertiary-container': '#794418',
        'error-container': '#93000a',
        'inverse-primary': '#006d36',
        'surface-container': '#201f1f',
        'tertiary': '#ffd9c1',
        'surface-bright': '#3a3939',
        'on-primary': '#003919',
        'outline': '#869486',
        'surface-dim': '#131313',
        'surface': '#131313',
        'secondary-container': '#ee9800',
        'secondary-fixed': '#ffddb8',
        'on-tertiary': '#4f2500',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'unit-1': '0.25rem',
        'unit-2': '0.5rem',
        'unit-3': '0.75rem',
        'unit-4': '1rem',
        'unit-6': '1.5rem',
        'unit-8': '2rem',
        'unit-12': '3rem',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'max-width': '1440px',
      },
      fontFamily: {
        'mono-label': ['"JetBrains Mono"', 'monospace'],
        'mono-code': ['"JetBrains Mono"', 'monospace'],
        'display-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'mono-label': ['13px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'mono-code': ['14px', { lineHeight: '1.7', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      keyframes: {
        progress: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(300%)' },
        },
        blink: {
          '50%': { opacity: '0' },
        },
      },
      animation: {
        'progress': 'progress 3s infinite linear',
        'blink': 'blink 1s step-end infinite',
      },
    },
  },
  plugins: [],
};
